  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - master
      - dev
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'run-jenkins')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ github.event }}
      run: echo "$GITHUB_CONTEXT"
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://54.202.108.130:32656/"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "hook"
